name: masang
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  mobx: ^1.2.1+1
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.28+1
  shared_preferences: ^0.5.7+3
  carousel_slider: ^2.2.1
  image_picker: ^0.6.7+4
  sliding_up_panel: ^1.0.2
  gradient_text: ^1.0.2
  url_launcher: ^5.5.0
  splashscreen:
  async: 
  flutter_mobx: ^1.1.0+1
  http: ^0.12.1
  share: ^0.6.4+3
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/img/logomasang.png
    - lib/assets/img/banner-img.png
    - lib/assets/img/drops.png
    - lib/assets/img/gota-de-sangue.png
    - lib/assets/img/4vidas.png
    - lib/assets/img/mao_celular.png
    - lib/assets/img/maps.png
    - lib/assets/img/notificacao.png
    - lib/assets/img/icone_doacao.png
    - lib/assets/icons/check.png
    - lib/assets/icons/edit.png
    - lib/assets/icons/home.png
    - lib/assets/icons/images.png
    - lib/assets/icons/leave.png
    - lib/assets/icons/share.png
    - lib/assets/icons/two_drop.png
    - lib/assets/icons/warning.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Teko
      fonts:
        - asset: lib/assets/fonts/Teko-Bold.ttf
        - asset: lib/assets/fonts/Teko-Light.ttf
        - asset: lib/assets/fonts/Teko-Medium.ttf
        - asset: lib/assets/fonts/Teko-Regular.ttf
        - asset: lib/assets/fonts/Teko-SemiBold.ttf
    - family: Helvetica
      fonts:
        - asset: lib/assets/fonts/Helvetica.ttf
        - asset: lib/assets/fonts/Helvetica-Bold.ttf
        - asset: lib/assets/fonts/Helvetica-BoldOblique.ttf
        - asset: lib/assets/fonts/helvetica-compressed.otf
        - asset: lib/assets/fonts/helvetica-light.ttf
        - asset: lib/assets/fonts/Helvetica-Oblique.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
