// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senai.GOcorrencia.Infra.Data.Context;

namespace Senai.GOcorrencia.Infra.Data.Migrations
{
    [DbContext(typeof(GOcorrenciaContext))]
    partial class GOcorrenciaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Senai.GOcorrencia.Dominio.Entities.AlunoDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnName("Celular")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnName("Curso")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Imagem")
                        .HasColumnName("Imagem")
                        .HasColumnType("varchar(3000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumMatricula")
                        .IsRequired()
                        .HasColumnName("NumeroMatricula")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ocorrencias")
                        .HasColumnName("Ocorrencias")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnName("Telefone")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Termo")
                        .IsRequired()
                        .HasColumnName("Termo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoCurso")
                        .IsRequired()
                        .HasColumnName("TipoCurso")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Turma")
                        .IsRequired()
                        .HasColumnName("Turma")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnName("Turno")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new { Id = 1, Celular = "(11)912341234", Curso = "Testando", Nome = "Teste", NumMatricula = "12345678", Status = true, Telefone = "(11)12341234", Termo = "1", TipoCurso = "Curso Teste", Turma = "1TT", Turno = "Teste" }
                    );
                });

            modelBuilder.Entity("Senai.GOcorrencia.Dominio.Entities.UsuarioDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnName("NIF")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("Senha")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnName("Tipo")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new { Id = 1, NIF = "123456789", Nome = "Teste", Senha = "123456", Tipo = "ADMINISTRADOR" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
